language: php

php:
  - 7.2

services:
  - mysql
  - postgresql

# This triggers builds to run on the new TravisCI infrastructure.
sudo: false

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'create database test;' -U postgres

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - bash -c 'wget https://scrutinizer-ci.com/ocular.phar'
    - bash -c 'php ocular.phar code-coverage:upload --format=php-clover coverage.clover'
